spring:
  application:
    name: commerce-coupon
  datasource:
    url: jdbc:mysql://localhost:13306/commerce
    username: hans
    password: hans-password
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
